### ISSUE TITLE
Readiness.IO Channel

### ISSUE THREAD

**Issue by Synysoul** [micblack/readiness-io-esp8266wifi#1]
I downloaded the library but i'm no sure how or if i need to open a new channel for my project.

am I doing something wrong?

**Comment by micblack** [comment]
Readiness.IO is undergoing some major changes under the hood and some restructuring to hopefully become fully open source. For now, the creation of new channels is disabled whereas existing channels are still operational. This library may not be current. Thank you for reaching out. I'll add a notice to the readme of similar effect.
